spring:
  application:
    name: Library Spring
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydatabase.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  sql:
    init:
      mode: always


