spring:
  application:
    name: Library Spring
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:mydatabase.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  sql:
    init:
      mode: always


springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /v3/api-docs
  title: Spring Library
  description: project to manage books
  version: 1.0.0